# Generated by Django 4.1.7 on 2023-05-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=True, upload_to='pics'),
        ),
    ]
